@namespace Rockstar
@classname Parser
@using System.Globalization

program <Prögram>
	= EOF
		{ new Prögram() }
	/  _? stmt:statement EOF
		{ new Prögram(stmt) }
	/  _? head:statement EOS tail:program
		{ tail.Insert(head) }

statement <Statement.Output>
	= output _ expr:expression { new Statement.Output(expr) }

output
	= "shout"

expression <Expression>
	= number

number <Number>
    = digits:([0-9]+ ("." [0-9]+)?) { new Number(Decimal.Parse(digits)) }

_	= [ \t]+
EOS	= _? ","
EOF	= !.
