// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "hOVQPOOOOQO'#C`'#C`QVQPOOOOQO-E6^-E6^",
  stateData: "_~OVOS~OQPORPO~O",
  goto: "[TPPPPUQQORRQ",
  nodeNames: "⚠ File ProperNoun CommonNoun",
  maxTerm: 7,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "#S~R[X^wpqw!c!}!l#T#o!z#y#zw$f$gw#BY#BZw$IS$I_w$I|$JOw$JT$JUw$KV$KWw&FU&FVw~|YV~X^wpqw#y#zw$f$gw#BY#BZw$IS$I_w$I|$JOw$JT$JUw$KV$KWw&FU&FVw~!oP#T#o!r~!wPQ~#T#o!r~#PPR~#T#o!z",
  tokenizers: [0],
  topRules: {"File":[0,1]},
  tokenPrec: 0
})
